kind: ConfigMap
apiVersion: v1
metadata:
  name: intuit-challenge
data:
  hibernate.hbm2ddl.auto: create
  hibernate.dialect: org.hibernate.dialect.HSQLDialect
  hibernate.show_sql: true
  spring.jpa.show-sql: true
  logging.level.org.hibernate.SQL: DEBUG
  logging.level.com.intuit.test.model.dao.in_mem: DEBUG
  logging.level.com.intuit.test.source_read.config_spring: INFO
  logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  data.source.file: sources/player.csv
  config.data.source: com.intuit.test.source_read.config_spring
  config.data.dao: com.intuit.test.model.dao.in_mem.config.spring
  config.rest.endpoint: com.intuit.test.rest.spring